name: Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  generate-documentation:
    runs-on: ubuntu-latest
    name: "Generate Documentation"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: make tfdocs-generate
      - name: Comparing generated Terraform documentation against main
        run: |
          git diff --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.4.*"
          - "1.5.*"
          - "1.6.*"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - env:
          TF_ACC: "1"
          DG_SERVICEBUS_CLIENTSECRET: ${{ secrets.DG_SERVICEBUS_CLIENTSECRET }}
          DG_SERVICEBUS_CLIENTID: ${{ vars.DG_SERVICEBUS_CLIENTID }}
        run: make testacc
        timeout-minutes: 10
